// French slug → German slug redirects for the DE site
// When a user lands on a French team slug, redirect 301 to the German canonical URL

export const frenchToGermanSlug: Record<string, string> = {
  "mexique": "mexiko",
  "afrique-du-sud": "suedafrika",
  "coree-du-sud": "suedkorea",
  "tchequie": "tschechien",
  "canada": "kanada",
  "suisse": "schweiz",
  "qatar": "katar",
  "bosnie-herzegovine": "bosnien-herzegowina",
  "bresil": "brasilien",
  "maroc": "marokko",
  "ecosse": "schottland",
  "haiti": "haiti",
  "etats-unis": "usa",
  "paraguay": "paraguay",
  "australie": "australien",
  "turquie": "tuerkei",
  "allemagne": "deutschland",
  "equateur": "ecuador",
  "cote-divoire": "elfenbeinkueste",
  "curacao": "curacao",
  "pays-bas": "niederlande",
  "japon": "japan",
  "tunisie": "tunesien",
  "suede": "schweden",
  "belgique": "belgien",
  "iran": "iran",
  "egypte": "aegypten",
  "nouvelle-zelande": "neuseeland",
  "espagne": "spanien",
  "uruguay": "uruguay",
  "arabie-saoudite": "saudi-arabien",
  "cap-vert": "kap-verde",
  "france": "frankreich",
  "senegal": "senegal",
  "norvege": "norwegen",
  "irak": "irak",
  "argentine": "argentinien",
  "autriche": "oesterreich",
  "algerie": "algerien",
  "jordanie": "jordanien",
  "portugal": "portugal",
  "colombie": "kolumbien",
  "ouzbekistan": "usbekistan",
  "rd-congo": "dr-kongo",
  "angleterre": "england",
  "croatie": "kroatien",
  "ghana": "ghana",
  "panama": "panama",
};

// Routes with simple team slugs: /mannschaft/, /prognose/, /kader/, /meister-wetten/
// Routes with compound match slugs (team1-vs-team2): /spiel/, /prognose-spiel/, /h2h/
