export type NewsCategory = "transferts" | "stades" | "billets" | "equipes" | "paris";

export interface NewsArticle {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  category: NewsCategory;
  tags: string[];
  imageEmoji: string;
}

// Legacy RSS imports have been removed. Public articles are now first-party MDX
// files generated by the editorial publisher under apps/fr/content/articles.
export const newsArticles: NewsArticle[] = [];

export const newsCategories: NewsCategory[] = [];

export const newsBySlug: Record<string, NewsArticle> = {};

export const newsByCategory: Record<NewsCategory, NewsArticle[]> = {
  transferts: [],
  stades: [],
  billets: [],
  equipes: [],
  paris: [],
};
