// ============================================================================
// Zod Schemas — Validate AI-generated JSON before caching
// Prevents hallucinated or malformed content from being served.
// ============================================================================

import { z } from "zod";

/** Match preview generated by Gemini Flash */
export const matchPreviewSchema = z.object({
  preview: z.string().min(1, "Preview cannot be empty"),
  keyFactors: z.array(z.string()).default([]),
  prediction: z.string().default(""),
  bettingAngle: z.string().default(""),
});

export type ValidatedMatchPreview = z.infer<typeof matchPreviewSchema>;

/** Single value bet from Claude expert analysis */
const valueBetSchema = z.object({
  market: z.string().min(1),
  selection: z.string().min(1),
  bookmakerOdds: z.coerce.number().min(1).max(1000),
  modelProbability: z.coerce.number().min(0).max(1),
  edge: z.coerce.number().min(-100).max(200),
  confidence: z.coerce.number().int().min(1).max(5),
  reasoning: z.string().min(1),
});

/** Expert insight generated by Claude Opus */
export const expertInsightSchema = z.object({
  valueBets: z.array(valueBetSchema).default([]),
  matchAnalysis: z.string().min(1, "Match analysis cannot be empty"),
  scorePrediction: z.string().default(""),
  keyInsight: z.string().default(""),
});

export type ValidatedExpertInsight = z.infer<typeof expertInsightSchema>;

/** Team analysis content */
export const teamAnalysisSchema = z.object({
  content: z.string().min(1, "Team analysis content cannot be empty"),
});

export type ValidatedTeamAnalysis = z.infer<typeof teamAnalysisSchema>;

/** Meta description — simple string validation */
export const metaDescriptionSchema = z.string().min(1).max(320);

/** Translation output — non-empty string */
export const translationSchema = z.string().min(1);

/** JSON-LD structured data — must be valid JSON string */
export const jsonLdSchema = z.string().min(2).refine(
  (val) => {
    try { JSON.parse(val); return true; } catch { return false; }
  },
  { message: "JSON-LD must be valid JSON" }
);
