export interface WorldCupEdition {
 year: number;
 host: string;
 hostFlag: string;
 winner: string;
 winnerFlag: string;
 runnerUp: string;
 runnerUpFlag: string;
 score: string;
 thirdPlace: string;
 thirdPlaceFlag: string;
 teams: number;
 topScorer: string;
 topScorerGoals: number;
}

export const editions: WorldCupEdition[] = [
 {
 year: 1930,
 host: "Uruguay",
 hostFlag: "🇺🇾",
 winner: "Uruguay",
 winnerFlag: "🇺🇾",
 runnerUp: "Argentine",
 runnerUpFlag: "🇦🇷",
 score: "4–2",
 thirdPlace: "États-Unis",
 thirdPlaceFlag: "🇺🇸",
 teams: 13,
 topScorer: "Guillermo Stábile (ARG)",
 topScorerGoals: 8,
 },
 {
 year: 1934,
 host: "Italie",
 hostFlag: "🇮🇹",
 winner: "Italie",
 winnerFlag: "🇮🇹",
 runnerUp: "Tchécoslovaquie",
 runnerUpFlag: "🇨🇿",
 score: "2–1 a.p.",
 thirdPlace: "Allemagne",
 thirdPlaceFlag: "🇩🇪",
 teams: 16,
 topScorer: "Oldřich Nejedly (TCH)",
 topScorerGoals: 5,
 },
 {
 year: 1938,
 host: "France",
 hostFlag: "🇫🇷",
 winner: "Italie",
 winnerFlag: "🇮🇹",
 runnerUp: "Hongrie",
 runnerUpFlag: "🇭🇺",
 score: "4–2",
 thirdPlace: "Brésil",
 thirdPlaceFlag: "🇧🇷",
 teams: 15,
 topScorer: "Leônidas (BRA)",
 topScorerGoals: 7,
 },
 {
 year: 1950,
 host: "Brésil",
 hostFlag: "🇧🇷",
 winner: "Uruguay",
 winnerFlag: "🇺🇾",
 runnerUp: "Brésil",
 runnerUpFlag: "🇧🇷",
 score: "2–1 (phase finale)",
 thirdPlace: "Suède",
 thirdPlaceFlag: "🇸🇪",
 teams: 13,
 topScorer: "Ademir (BRA)",
 topScorerGoals: 9,
 },
 {
 year: 1954,
 host: "Suisse",
 hostFlag: "🇨🇭",
 winner: "Allemagne",
 winnerFlag: "🇩🇪",
 runnerUp: "Hongrie",
 runnerUpFlag: "🇭🇺",
 score: "3–2",
 thirdPlace: "Autriche",
 thirdPlaceFlag: "🇦🇹",
 teams: 16,
 topScorer: "Sándor Kocsis (HUN)",
 topScorerGoals: 11,
 },
 {
 year: 1958,
 host: "Suède",
 hostFlag: "🇸🇪",
 winner: "Brésil",
 winnerFlag: "🇧🇷",
 runnerUp: "Suède",
 runnerUpFlag: "🇸🇪",
 score: "5–2",
 thirdPlace: "France",
 thirdPlaceFlag: "🇫🇷",
 teams: 16,
 topScorer: "Just Fontaine (FRA)",
 topScorerGoals: 13,
 },
 {
 year: 1962,
 host: "Chili",
 hostFlag: "🇨🇱",
 winner: "Brésil",
 winnerFlag: "🇧🇷",
 runnerUp: "Tchécoslovaquie",
 runnerUpFlag: "🇨🇿",
 score: "3–1",
 thirdPlace: "Chili",
 thirdPlaceFlag: "🇨🇱",
 teams: 16,
 topScorer: "Garrincha, Vavá, Leonel Sánchez, Drazan Jerkovic, Valentin Ivanov, Florian Albert",
 topScorerGoals: 4,
 },
 {
 year: 1966,
 host: "Angleterre",
 hostFlag: "",
 winner: "Angleterre",
 winnerFlag: "",
 runnerUp: "Allemagne",
 runnerUpFlag: "🇩🇪",
 score: "4–2 a.p.",
 thirdPlace: "Portugal",
 thirdPlaceFlag: "🇵🇹",
 teams: 16,
 topScorer: "Eusébio (POR)",
 topScorerGoals: 9,
 },
 {
 year: 1970,
 host: "Mexique",
 hostFlag: "🇲🇽",
 winner: "Brésil",
 winnerFlag: "🇧🇷",
 runnerUp: "Italie",
 runnerUpFlag: "🇮🇹",
 score: "4–1",
 thirdPlace: "Allemagne",
 thirdPlaceFlag: "🇩🇪",
 teams: 16,
 topScorer: "Gerd Müller (FRG)",
 topScorerGoals: 10,
 },
 {
 year: 1974,
 host: "Allemagne",
 hostFlag: "🇩🇪",
 winner: "Allemagne",
 winnerFlag: "🇩🇪",
 runnerUp: "Pays-Bas",
 runnerUpFlag: "🇳🇱",
 score: "2–1",
 thirdPlace: "Pologne",
 thirdPlaceFlag: "🇵🇱",
 teams: 16,
 topScorer: "Grzegorz Lato (POL)",
 topScorerGoals: 7,
 },
 {
 year: 1978,
 host: "Argentine",
 hostFlag: "🇦🇷",
 winner: "Argentine",
 winnerFlag: "🇦🇷",
 runnerUp: "Pays-Bas",
 runnerUpFlag: "🇳🇱",
 score: "3–1 a.p.",
 thirdPlace: "Brésil",
 thirdPlaceFlag: "🇧🇷",
 teams: 16,
 topScorer: "Mario Kempes (ARG)",
 topScorerGoals: 6,
 },
 {
 year: 1982,
 host: "Espagne",
 hostFlag: "🇪🇸",
 winner: "Italie",
 winnerFlag: "🇮🇹",
 runnerUp: "Allemagne",
 runnerUpFlag: "🇩🇪",
 score: "3–1",
 thirdPlace: "Pologne",
 thirdPlaceFlag: "🇵🇱",
 teams: 24,
 topScorer: "Paolo Rossi (ITA)",
 topScorerGoals: 6,
 },
 {
 year: 1986,
 host: "Mexique",
 hostFlag: "🇲🇽",
 winner: "Argentine",
 winnerFlag: "🇦🇷",
 runnerUp: "Allemagne",
 runnerUpFlag: "🇩🇪",
 score: "3–2",
 thirdPlace: "France",
 thirdPlaceFlag: "🇫🇷",
 teams: 24,
 topScorer: "Gary Lineker (ENG)",
 topScorerGoals: 6,
 },
 {
 year: 1990,
 host: "Italie",
 hostFlag: "🇮🇹",
 winner: "Allemagne",
 winnerFlag: "🇩🇪",
 runnerUp: "Argentine",
 runnerUpFlag: "🇦🇷",
 score: "1–0",
 thirdPlace: "Italie",
 thirdPlaceFlag: "🇮🇹",
 teams: 24,
 topScorer: "Salvatore Schillaci (ITA)",
 topScorerGoals: 6,
 },
 {
 year: 1994,
 host: "États-Unis",
 hostFlag: "🇺🇸",
 winner: "Brésil",
 winnerFlag: "🇧🇷",
 runnerUp: "Italie",
 runnerUpFlag: "🇮🇹",
 score: "0–0 a.p. (3–2 tab)",
 thirdPlace: "Suède",
 thirdPlaceFlag: "🇸🇪",
 teams: 24,
 topScorer: "Hristo Stoïchkov (BUL), Oleg Salenko (RUS)",
 topScorerGoals: 6,
 },
 {
 year: 1998,
 host: "France",
 hostFlag: "🇫🇷",
 winner: "France",
 winnerFlag: "🇫🇷",
 runnerUp: "Brésil",
 runnerUpFlag: "🇧🇷",
 score: "3–0",
 thirdPlace: "Croatie",
 thirdPlaceFlag: "🇭🇷",
 teams: 32,
 topScorer: "Davor Šuker (CRO)",
 topScorerGoals: 6,
 },
 {
 year: 2002,
 host: "Corée/Japon",
 hostFlag: "🇰🇷🇯🇵",
 winner: "Brésil",
 winnerFlag: "🇧🇷",
 runnerUp: "Allemagne",
 runnerUpFlag: "🇩🇪",
 score: "2–0",
 thirdPlace: "Turquie",
 thirdPlaceFlag: "🇹🇷",
 teams: 32,
 topScorer: "Ronaldo (BRA)",
 topScorerGoals: 8,
 },
 {
 year: 2006,
 host: "Allemagne",
 hostFlag: "🇩🇪",
 winner: "Italie",
 winnerFlag: "🇮🇹",
 runnerUp: "France",
 runnerUpFlag: "🇫🇷",
 score: "1–1 a.p. (5–3 tab)",
 thirdPlace: "Allemagne",
 thirdPlaceFlag: "🇩🇪",
 teams: 32,
 topScorer: "Miroslav Klose (GER)",
 topScorerGoals: 5,
 },
 {
 year: 2010,
 host: "Afrique du Sud",
 hostFlag: "🇿🇦",
 winner: "Espagne",
 winnerFlag: "🇪🇸",
 runnerUp: "Pays-Bas",
 runnerUpFlag: "🇳🇱",
 score: "1–0 a.p.",
 thirdPlace: "Allemagne",
 thirdPlaceFlag: "🇩🇪",
 teams: 32,
 topScorer: "Thomas Müller (GER), David Villa (ESP), Wesley Sneijder (NED), Diego Forlán (URU)",
 topScorerGoals: 5,
 },
 {
 year: 2014,
 host: "Brésil",
 hostFlag: "🇧🇷",
 winner: "Allemagne",
 winnerFlag: "🇩🇪",
 runnerUp: "Argentine",
 runnerUpFlag: "🇦🇷",
 score: "1–0 a.p.",
 thirdPlace: "Pays-Bas",
 thirdPlaceFlag: "🇳🇱",
 teams: 32,
 topScorer: "James Rodríguez (COL)",
 topScorerGoals: 6,
 },
 {
 year: 2018,
 host: "Russie",
 hostFlag: "🇷🇺",
 winner: "France",
 winnerFlag: "🇫🇷",
 runnerUp: "Croatie",
 runnerUpFlag: "🇭🇷",
 score: "4–2",
 thirdPlace: "Belgique",
 thirdPlaceFlag: "🇧🇪",
 teams: 32,
 topScorer: "Harry Kane (ENG)",
 topScorerGoals: 6,
 },
 {
 year: 2022,
 host: "Qatar",
 hostFlag: "🇶🇦",
 winner: "Argentine",
 winnerFlag: "🇦🇷",
 runnerUp: "France",
 runnerUpFlag: "🇫🇷",
 score: "3–3 a.p. (4–2 tab)",
 thirdPlace: "Croatie",
 thirdPlaceFlag: "🇭🇷",
 teams: 32,
 topScorer: "Kylian Mbappé (FRA)",
 topScorerGoals: 8,
 },
];

export interface CountryRecord {
 country: string;
 flag: string;
 titles: number;
 finals: number;
 years: number[];
 confederation: string;
}

export const countryRecords: CountryRecord[] = [
 {
 country: "Brésil",
 flag: "🇧🇷",
 titles: 5,
 finals: 7,
 years: [1958, 1962, 1970, 1994, 2002],
 confederation: "CONMEBOL",
 },
 {
 country: "Allemagne",
 flag: "🇩🇪",
 titles: 4,
 finals: 8,
 years: [1954, 1974, 1990, 2014],
 confederation: "UEFA",
 },
 {
 country: "Italie",
 flag: "🇮🇹",
 titles: 4,
 finals: 6,
 years: [1934, 1938, 1982, 2006],
 confederation: "UEFA",
 },
 {
 country: "Argentine",
 flag: "🇦🇷",
 titles: 3,
 finals: 5,
 years: [1978, 1986, 2022],
 confederation: "CONMEBOL",
 },
 {
 country: "France",
 flag: "🇫🇷",
 titles: 2,
 finals: 3,
 years: [1998, 2018],
 confederation: "UEFA",
 },
 {
 country: "Uruguay",
 flag: "🇺🇾",
 titles: 2,
 finals: 2,
 years: [1930, 1950],
 confederation: "CONMEBOL",
 },
 {
 country: "Espagne",
 flag: "🇪🇸",
 titles: 1,
 finals: 1,
 years: [2010],
 confederation: "UEFA",
 },
 {
 country: "Angleterre",
 flag: "",
 titles: 1,
 finals: 1,
 years: [1966],
 confederation: "UEFA",
 },
];

export const records = [
 {
 icon: " ",
 label: "Meilleur buteur de l'histoire",
 value: "Miroslav Klose",
 detail: "16 buts (Allemagne, 2002–2014)",
 },
 {
 icon: "",
 label: "Plus de matchs joués",
 value: "Lothar Matthäus",
 detail: "25 matchs (Allemagne, 1982–1998)",
 },
 {
 icon: " ",
 label: "Plus de titres (joueur)",
 value: "Pelé",
 detail: "3 titres (Brésil, 1958, 1962, 1970)",
 },
 {
 icon: "",
 label: "Plus jeune buteur",
 value: "Pelé",
 detail: "17 ans, 239 jours (Brésil vs Pays de Galles, 1958)",
 },
 {
 icon: "",
 label: "Plus vieux buteur",
 value: "Roger Milla",
 detail: "42 ans, 39 jours (Cameroun vs Russie, 1994)",
 },
 {
 icon: " ",
 label: "Record buts en 1 tournoi",
 value: "Just Fontaine",
 detail: "13 buts (France, 1958) — record imbattable",
 },
 {
 icon: " ",
 label: "Plus grand nombre de CDM",
 value: "Antonio Carbajal & Lothar Matthäus",
 detail: "5 Coupes du Monde chacun",
 },
 {
 icon: "",
 label: "Pays à avoir remporté la CDM",
 value: "8 nations",
 detail: "Brésil, Allemagne, Italie, Argentine, France, Uruguay, Espagne, Angleterre",
 },
 {
 icon: " ",
 label: "Plus grande victoire",
 value: "Hongrie 10–1 Salvador",
 detail: "Phase de groupes, 1982",
 },
 {
 icon: "",
 label: "Plus grande déroute en finale",
 value: "Brésil 0–3 France (finale 1998)",
 detail: "Ronaldo joue malgré une crise d'épilepsie la veille",
 },
 {
 icon: "",
 label: "Pays hôte vainqueur",
 value: "6 fois",
 detail: "Uruguay 1930, Italie 1934, Angleterre 1966, Allemagne 1974, Argentine 1978, France 1998",
 },
 {
 icon: "",
 label: "Édition 2026",
 value: "48 équipes, 104 matchs",
 detail: "USA, Canada, Mexique — 3 pays co-organisateurs",
 },
];
